### PR TITLE
Fixed bug in iptables 1.8

### PR DESCRIPTION
**Pull request by jvinolas**
Fixes bug using backports

### CODE REVIEW

**Review by sim6 — CHANGES_REQUESTED** [review]
I prefer to put the repository line to `/etc/apt/sources.list.d/backports.list`
After that we need to run `apt update`
And finally an `apt install -y iptables -t buster-backports` instead of `apt  upgrade ...`

**Comment by jvinolas** [comment]
Yes, you're right. I missed the apt update and it is better in it's own sources file. 

One thing I've realized is that after upgrading iptables from backports it upgrades a lot of packages, also the kernel to the latest version. We should be aware of that.

**Comment by sim6** [comment]
As we agreed via IM, I'll take care of this.

**Comment by sim6** [comment]
@jvinolas, please, could you review my changes?

**Review by NefixEstrada — APPROVED** [review]

**Comment by sim6** [comment]
:)

**Pull request merged**
