### PR TITLE
added novideo hypervisor

### PR DESCRIPTION
**Pull request by jvinolas**
When using a dedicated video proxy the remote hypervisors should be run without the video proxies and should also open ports 5900-6899 for video requests coming from the video proxy host. 
Of cours this ports should be opened ONLY from the video proxy host.

### CODE REVIEW

**Review by sim6 — COMMENTED** [review]
Publishing this ports with the current build.sh generates a big docker-compose files for all flavors. I think would be better to create an yml with only this ports and only include it in `novideo-hypervisor.yml`.

**Comment by jvinolas** [comment]
Ok, I'v split the config so now you can build hypervisor or standalone-hypervisor.

**Review by sim6 — CHANGES_REQUESTED** [review]
We don't need to duplicate the content of `isard-hypervisor.yml` and `isard-hypervisor-vlans.yml`.

We can create a file with the following content:
```
version: "3.5"
services:
  isard-hypervisor:
    ports:
    - "5900-6899:5900-6899"
```
And merge it with the current one.
Ex. `docker-compose -f isard-hypervisor.yml -f isard-hypervisor-ports.yml config > standalone-hypervisor.yml`

**Comment by sim6** [comment]
This is blocking #248

**Comment by sim6** [comment]
As we agreed, I applied my requested changes and squashed them. Please @jvinolas, could you review them?

**Review by sim6 — DISMISSED** [review]
But I'm co-authored.

**Comment by jvinolas** [comment]
Ok. We can merge this one.

**Review by sim6 — APPROVED** [review]
So, I'm merging it.

**Pull request merged**
