### PR TITLE
added user network

### PR DESCRIPTION
**Pull request by jvinolas**
In resources added 'user' type network that engine will parse and add a user personal network to started desktops.

### CODE REVIEW

**Comment by alarraz** [comment]
ok, now we need a pull request from engine changes

**Review by alarraz — APPROVED** [review]
ok

**Review by sim6 — CHANGES_REQUESTED** [review]
As https://github.com/isard-vdi/isard/pull/257#issuecomment-706744299 we need the engine changes before merging.

**Comment by jvinolas** [comment]
True, we are waiting for @alarraz to finish tests on engine part.

**Pull request closed without merging**
