### PR TITLE
Force hypervisor

### PR DESCRIPTION
**Pull request by jvinolas**
This will let managers and administrator roles to force an hypervisor for a desktop or template. This is useful right now when you want to use shared network between hosts and you don't want to mess with infrastructure configurations: just force those desktops or the template from where are derived to an hypervisor.

The derived desktops will inherit the forced_domain defined in parent template at creation time.
The templates created from a desktop with forced_hyp will not inherit that parameter. It can be set in the newly created template if needed for next derived desktops.

### CODE REVIEW

**Review by sim6 — DISMISSED** [review]
It works for me but I don't inspected the code. Please, clould you squash commits?

**Review by sim6 — CHANGES_REQUESTED** [review]
It doesn't work for me. The desktop starts on an unforced hypervisor.

**Comment by jvinolas** [comment]
Not it is fixed at engine level

**Review by sim6 — CHANGES_REQUESTED** [review]
Works for me. Please, could you clean it squashing commits with a usefull message, removing comments, unneeded yaml files and trailing whitespaces?

**Review by sim6 — APPROVED** [review]
Thank you very much!

**Pull request merged**
